title: "どこに置いていいかわからないちょっとしたスニペットたちの供養所"
summary: |-
  昔にQiitaなどで公開するために即興で書いたけど、検索する時に困ったあれこれを一元管理したいためだけにまとめました。
  スニペットを作って、そこに記事をまとめる方針を採用しがちでしたが、管理を考えると本の方がいいかな、という印象です。

  現状、特に有料化は考えていません。
  これらのスクリプトたちが、どこかで誰かのお役に立てれば嬉しいです。
topics: ["供養", "スニペット"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - changelog_zenn
  - shell_translate
  - gas2readme_md
  - translate_text
  - mirror_repository
  - github_page_cname
  - wordpress_static

