title: "【無料 / 🔰コメント募集】Zennで使いたいテンプレート"
summary: |-
  自分用ですが、需要がある人に使ってもらえれば、と思って公開してます。
  良い方法（フォーマット）や使用感のフィードバック、あるいはカスタマイズ例をいただけると喜びます。

  - 📖この本のコンテンツは追記しながら書いています。
  - 💵この本は有料にしません。ご安心ください。
  - ❗この本のコンテンツの一部を差し替えたり、URLを変更する可能性があるのでブックマークはこのページにお願いします。
  - 🪧この本の記事へのコメント時は、どの記事へのコメントか明示してもらえると助かります。
topics: ["テンプレート", "自分用"]
published: true
price: 0
chapters:
  - template_article
  - template_book_yaml
  - template_book_md
  - template_scrap
  - changelog_zenn
  - explanation_book_md
