title: "他の方の記事へのコメントで自分語りしたくないための本"
summary: |-
  他の方の記事へのコメントです。
  私はコメント欄で自分が喋りたいだけの自論を展開するのは失礼だと考えているので、自前で記事を書いてコメントをするようにしています。
  Twitterだと「エアリプ」と呼ばれる行為ですね。
  エアリプですが、原文を叩く目的はゼロです。叩く目的ならリスクしかないのでそもそもコメントしません。

  ご本人の許可が得られれば、元記事の方へリンクコメントを残させていただいています。

  - この本は有料にしません。ご安心ください。
  - この本の記事へのコメント時は、どの記事へのコメントか明示してもらえると助かります。
topics: ["コメント"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - uhyo-technical-articles
