title: "のむらやのプロフィール"
summary: |-
  この記事を書いている人はどういう人間なのか、気にしていますか？
  同じ事でも「誰が言うか」で信頼性が変わります。
  特に、ネットの海に漂う情報は誰が情報源なのかをあなた自身でしっかりと管理する必要があります。

  この本は、そういった「情報源が信頼できるのか」の助けになれば幸いです。

  【この本は有料にしません】
topics: ["プロフィール", "利用規約"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - CHANGELOG_zenn
  - want_to_zenn
  - attention_agreement
  - team_of_service
