name: Qiita記事のバックアップ、Zennへの投稿、ドキュメントのビルドとデプロイ

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # バックアップと投稿を毎日実行

jobs:
  backup_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Pythonの依存関係をキャッシュする
        id: cache-python-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 依存関係をインストール
        if: steps.cache-python-deps.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt  # pyファイルとsphinx、テーマを含む

      - name: Qiita記事をバックアップ
        run: python src/backup_qiita_articles.py --access-token ${{ secrets.QIITA_API_TOKEN }}

      - name: Zennへ投稿できるファイル配置に変更
        run: python src/convert_to_zenn_format.py

      # - name: py-docstringをhtmlビルドしてホスティングする
      #   run: |
      #     pdoc src/backup_qiita_articles.py --html -o docs
      #     pdoc src/convert_to_zenn_format.py --html -o docs

      - name: 変更をコミットし、Zennに投稿
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "backup_and_publish"
          git push origin main
