name: Qiita記事のバックアップ、Zennへの投稿、ドキュメントのビルドとデプロイ

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # バックアップと投稿を毎日実行

jobs:
  backup_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Pythonの依存関係をキャッシュする
        id: cache-python-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 依存関係をインストール
        if: steps.cache-python-deps.outputs.cache-hit != 'true'
        run: pip install -r docs/requirements.txt  # pyファイルとsphinx、テーマを含む

      - name: Qiita記事をバックアップ
        run: python src/backup_qiita_articles.py --access-token ${{ secrets.QIITA_API_TOKEN }}

      - name: Zennへ投稿
        run: python src/convert_to_zenn_format.py

      - name: Sphinxドキュメントをビルド
        run: |
          cd docs  # ドキュメントソースがあるディレクトリに移動
          make html  # SphinxドキュメントをHTMLにビルド

      - name: SphinxドキュメントをGitHub Pagesにデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html  # ビルドされたHTMLを指定
