name: Qiita記事のバックアップ、Zennへの投稿（デプロイ）

on:
  schedule:
    - cron: '0 0 * * *'  # バックアップと投稿を毎日実行

jobs:
  backup_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: 依存関係をインストール。キャッシュする案もあったが安定しなかったので廃止
        run: |
          python -m pip install --upgrade pip  # pip自体をアップグレード
          pip install -r requirements.txt  # pyファイルのみ。pdoc3はpushをトリガーにしたCIで実行させる

      - name: Qiita記事をバックアップ
        run: python src/backup_qiita_articles.py --access-token ${{ secrets.QIITA_API_TOKEN }}

      - name: Zennへ投稿できるファイル配置に変更
        run: python src/convert_to_zenn_format.py

      - name: 変更をコミットし、Zennに投稿。変更がなければ何もしない
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "backup_and_publish"
            git push origin main
          fi
          
